EBandPlannerROS:
  Ctrl_Rate : 20
  differential_drive: True
  k_prop: 4
  k_damp: 1
  max_acceleration: 1
  max_translational_acceleration: 1
  max_rotational_acceleration: 1
  max_vel_lin: 0.4
  max_vel_th: 0.4
  min_vel_lin: 0.04
  min_vel_th: 0.04
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1

