EBandPlannerROS:
  Ctrl_Rate : 20
  differential_drive: True
  k_prop: 1
  k_damp: 1
  max_acceleration: 1
  max_translational_acceleration: 1
  max_rotational_acceleration: 1
  max_vel_lin: 0.3
  max_vel_th: 0.3
  min_vel_lin: 0.08
  min_vel_th: 0.08
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1

